import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { HiOutlineDocumentReport, HiOutlineDownload, HiOutlineChevronRight } from 'react-icons/hi';
import api from '../services/api';
import toast from 'react-hot-toast';

const ReportsPage = () => {
  const [workflows, setWorkflows] = useState([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    fetchCompletedWorkflows();
  }, []);

  const fetchCompletedWorkflows = async () => {
    try {
      const res = await api.get('/workflow');
      const completed = (res.data.data || []).filter(w => w.status === 'completed');
      setWorkflows(completed);
    } catch (err) {
      toast.error('Failed to load reports');
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async (workflowId, format) => {
    try {
      const response = await api.post(`/reports/workflow/${workflowId}/export/${format}`, {}, {
        responseType: 'blob',
      });
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `ClaurusIQ-Report.${format}`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      toast.success(`${format.toUpperCase()} exported successfully`);
    } catch (err) {
      toast.error(`Export failed: ${err.message}`);
    }
  };

  if (loading) {
    return (
      <div className="flex h-[60vh] items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-4 border-primary-500 border-t-transparent"></div>
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="max-w-5xl mx-auto"
    >
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
          <HiOutlineDocumentReport className="text-violet-500" />
          Report Intelligence
        </h1>
        <p className="text-slate-500 dark:text-slate-400 mt-1">
          View and export publication-ready research reports generated by the AI pipeline.
        </p>
      </div>

      {workflows.length === 0 ? (
        <div className="text-center py-20 bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800">
          <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-violet-500/10 to-purple-500/10 flex items-center justify-center mb-6 mx-auto">
            <HiOutlineDocumentReport className="w-10 h-10 text-violet-500" />
          </div>
          <h3 className="text-lg font-bold text-slate-900 dark:text-white">No Reports Available</h3>
          <p className="text-slate-500 mt-2 max-w-md mx-auto">
            Complete a research workflow to generate an executive intelligence report.
          </p>
          <button
            onClick={() => navigate('/dashboard/research')}
            className="mt-6 px-6 py-2.5 bg-primary-600 hover:bg-primary-500 text-white font-semibold rounded-xl transition-colors"
          >
            Start Research
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          {workflows.map((wf) => (
            <div
              key={wf._id}
              className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 hover:shadow-md transition-shadow"
            >
              <div className="flex flex-col sm:flex-row gap-4 justify-between sm:items-center">
                <div className="flex-1 min-w-0">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white truncate">
                    {wf.query}
                  </h3>
                  <div className="flex flex-wrap items-center gap-3 mt-2">
                    <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-400 uppercase">
                      Completed
                    </span>
                    <span className="text-sm text-slate-500">
                      {new Date(wf.createdAt).toLocaleDateString()} at {new Date(wf.createdAt).toLocaleTimeString()}
                    </span>
                    <span className="text-sm text-slate-500">
                      {wf.agents.filter(a => a.status === 'completed').length}/{wf.agents.length} agents
                    </span>
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <button
                    onClick={() => handleExport(wf._id, 'json')}
                    className="px-3 py-1.5 text-xs font-bold bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
                  >
                    <HiOutlineDownload className="w-3.5 h-3.5 inline mr-1" />
                    JSON
                  </button>
                  <button
                    onClick={() => handleExport(wf._id, 'markdown')}
                    className="px-3 py-1.5 text-xs font-bold bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
                  >
                    <HiOutlineDownload className="w-3.5 h-3.5 inline mr-1" />
                    MD
                  </button>
                  <button
                    onClick={() => handleExport(wf._id, 'html')}
                    className="px-3 py-1.5 text-xs font-bold bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
                  >
                    <HiOutlineDownload className="w-3.5 h-3.5 inline mr-1" />
                    HTML
                  </button>
                  <button
                    onClick={() => navigate('/dashboard/workspace')}
                    className="px-3 py-1.5 text-xs font-bold bg-primary-600 text-white rounded-lg hover:bg-primary-500 transition-colors flex items-center gap-1"
                  >
                    View
                    <HiOutlineChevronRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </motion.div>
  );
};

export default ReportsPage;
