const PDFDocument = require('pdfkit');

class PDFGenerator {
  static async generate(report, res) {
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-disposition', `attachment; filename=Report-${report._id}.pdf`);
    res.setHeader('Content-type', 'application/pdf');

    doc.pipe(res);

    // Cover Page
    doc.fontSize(28).font('Helvetica-Bold').text('Executive Intelligence Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(16).font('Helvetica').text(`Generated by ClaurusIQ`, { align: 'center' });
    doc.moveDown(4);

    // Executive Summary
    if (report.executiveSummary) {
      doc.addPage();
      doc.fontSize(22).font('Helvetica-Bold').text('Executive Summary', { underline: true });
      doc.moveDown();
      doc.fontSize(14).font('Helvetica-Bold').text('Objective');
      doc.fontSize(12).font('Helvetica').text(report.executiveSummary.objective);
      doc.moveDown();
      doc.fontSize(14).font('Helvetica-Bold').text('Conclusion');
      doc.fontSize(12).font('Helvetica').text(report.executiveSummary.conclusion);
    }

    // Key Findings
    if (report.keyFindings && report.keyFindings.topDiscoveries) {
      doc.addPage();
      doc.fontSize(22).font('Helvetica-Bold').text('Key Findings', { underline: true });
      doc.moveDown();
      report.keyFindings.topDiscoveries.forEach((finding, index) => {
        doc.fontSize(12).font('Helvetica-Bold').text(`${index + 1}. ${finding.claim}`);
        doc.fontSize(10).font('Helvetica-Oblique').text(`Confidence: ${finding.confidence} | Support: ${finding.supportCount}`);
        doc.moveDown();
      });
    }

    doc.end();
  }
}

module.exports = PDFGenerator;
