const pptxgen = require('pptxgenjs');

class PowerPointGenerator {
  static async generate(report, res) {
    const pptx = new pptxgen();

    // Title Slide
    let slide = pptx.addSlide();
    slide.addText('Executive Intelligence Report', { x: 1, y: 2, fontSize: 24, bold: true, align: 'center' });
    slide.addText('Generated by ClaurusIQ', { x: 1, y: 3, fontSize: 14, align: 'center' });

    // Executive Summary
    if (report.executiveSummary) {
      slide = pptx.addSlide();
      slide.addText('Executive Summary', { x: 0.5, y: 0.5, fontSize: 18, bold: true });
      slide.addText(report.executiveSummary.conclusion, { x: 0.5, y: 1.5, fontSize: 12 });
    }

    const buffer = await pptx.write('nodebuffer');
    
    res.setHeader('Content-disposition', `attachment; filename=Report-${report._id}.pptx`);
    res.setHeader('Content-type', 'application/vnd.openxmlformats-officedocument.presentationml.presentation');
    res.send(buffer);
  }
}

module.exports = PowerPointGenerator;
