const docx = require('docx');
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = docx;

class WordGenerator {
  static async generate(report, res) {
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: "Executive Intelligence Report",
            heading: HeadingLevel.TITLE,
          }),
          new Paragraph({
            text: "Generated by ClaurusIQ",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "Conclusion: ",
                bold: true,
              }),
              new TextRun(report.executiveSummary?.conclusion || ""),
            ],
          }),
        ],
      }],
    });

    const b64string = await Packer.toBase64String(doc);
    const buffer = Buffer.from(b64string, 'base64');

    res.setHeader('Content-disposition', `attachment; filename=Report-${report._id}.docx`);
    res.setHeader('Content-type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.send(buffer);
  }
}

module.exports = WordGenerator;
